import { Timetable } from '@/types'

export const sampleTimetable: Timetable = {
  id: 'sample-1',
  title: 'Little Thurrock Primary School - Class 2EJ',
  description: 'Spring 2 Week 2 - Teacher: Miss Joynes',
  teacherId: 'teacher-1',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  teacher: {
    id: 'teacher-1',
    name: 'Miss Joynes',
    email: 'miss.joynes@school.com'
  },
  timeblocks: [
    // Monday
    {
      id: 'block-1',
      title: 'Registration and Early Morning work',
      description: 'Daily registration and morning activities',
      startTime: '08:35',
      endTime: '08:50',
      dayOfWeek: 'Monday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-2',
      title: 'RWI',
      description: 'Read Write Inc phonics',
      startTime: '09:00',
      endTime: '09:30',
      dayOfWeek: 'Monday',
      duration: 30,
      color: '#3B82F6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-3',
      title: 'Maths Consolidation',
      description: 'Maths practice and consolidation',
      startTime: '09:30',
      endTime: '10:00',
      dayOfWeek: 'Monday',
      duration: 30,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-4',
      title: 'Assembly',
      description: 'School assembly',
      startTime: '10:00',
      endTime: '10:15',
      dayOfWeek: 'Monday',
      duration: 15,
      color: '#8B5CF6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-5',
      title: 'Break',
      description: 'Morning break',
      startTime: '10:20',
      endTime: '10:35',
      dayOfWeek: 'Monday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-6',
      title: 'Maths Cont',
      description: 'Maths continuation',
      startTime: '10:35',
      endTime: '10:50',
      dayOfWeek: 'Monday',
      duration: 15,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-7',
      title: 'English Experience Day',
      description: 'English experience and activities',
      startTime: '10:50',
      endTime: '12:00',
      dayOfWeek: 'Monday',
      duration: 70,
      color: '#10B981',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-8',
      title: 'Lunch',
      description: 'Lunch break',
      startTime: '12:00',
      endTime: '13:00',
      dayOfWeek: 'Monday',
      duration: 60,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-9',
      title: 'Handwriting',
      description: 'Handwriting practice',
      startTime: '13:00',
      endTime: '13:15',
      dayOfWeek: 'Monday',
      duration: 15,
      color: '#6B7280',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-10',
      title: 'History',
      description: 'Inside the Titanic',
      startTime: '13:15',
      endTime: '14:15',
      dayOfWeek: 'Monday',
      duration: 60,
      color: '#EF4444',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-11',
      title: 'Computing',
      description: 'Data (Tally Charts) Pictogram',
      startTime: '14:15',
      endTime: '15:10',
      dayOfWeek: 'Monday',
      duration: 55,
      color: '#06B6D4',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-12',
      title: 'Storytime',
      description: 'Story time',
      startTime: '15:00',
      endTime: '15:15',
      dayOfWeek: 'Monday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // Tuesday
    {
      id: 'block-13',
      title: 'Registration and Early Morning work',
      description: 'Daily registration and morning activities',
      startTime: '08:35',
      endTime: '08:50',
      dayOfWeek: 'Tuesday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-14',
      title: 'RWI',
      description: 'Read Write Inc phonics',
      startTime: '09:00',
      endTime: '09:30',
      dayOfWeek: 'Tuesday',
      duration: 30,
      color: '#3B82F6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-15',
      title: 'English',
      description: 'Sentence Stack 5',
      startTime: '09:30',
      endTime: '10:20',
      dayOfWeek: 'Tuesday',
      duration: 50,
      color: '#10B981',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-16',
      title: 'Break',
      description: 'Morning break',
      startTime: '10:20',
      endTime: '10:35',
      dayOfWeek: 'Tuesday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-17',
      title: 'PHSE',
      description: 'Lesson 2 What is Money and how to keep it safe',
      startTime: '10:35',
      endTime: '11:00',
      dayOfWeek: 'Tuesday',
      duration: 25,
      color: '#8B5CF6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-18',
      title: 'Music',
      description: 'Glocks booked at 11:30',
      startTime: '11:00',
      endTime: '12:00',
      dayOfWeek: 'Tuesday',
      duration: 60,
      color: '#F97316',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-19',
      title: 'Lunch',
      description: 'Lunch break',
      startTime: '12:00',
      endTime: '13:00',
      dayOfWeek: 'Tuesday',
      duration: 60,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-20',
      title: 'Handwriting',
      description: 'Handwriting practice',
      startTime: '13:00',
      endTime: '13:15',
      dayOfWeek: 'Tuesday',
      duration: 15,
      color: '#6B7280',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-21',
      title: 'Maths',
      description: 'Compare and order time',
      startTime: '13:15',
      endTime: '13:45',
      dayOfWeek: 'Tuesday',
      duration: 30,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-22',
      title: 'Science',
      description: 'Natural and man-made materials',
      startTime: '14:00',
      endTime: '15:00',
      dayOfWeek: 'Tuesday',
      duration: 60,
      color: '#84CC16',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-23',
      title: 'Storytime',
      description: 'Story time',
      startTime: '15:00',
      endTime: '15:15',
      dayOfWeek: 'Tuesday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // Wednesday
    {
      id: 'block-24',
      title: 'Registration and Early Morning work',
      description: 'Daily registration and morning activities',
      startTime: '08:35',
      endTime: '08:50',
      dayOfWeek: 'Wednesday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-25',
      title: 'RWI',
      description: 'Read Write Inc phonics',
      startTime: '09:00',
      endTime: '09:30',
      dayOfWeek: 'Wednesday',
      duration: 30,
      color: '#3B82F6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-26',
      title: 'Maths',
      description: 'Compare and order time',
      startTime: '09:30',
      endTime: '10:00',
      dayOfWeek: 'Wednesday',
      duration: 30,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-27',
      title: 'In Class Assembly',
      description: 'Class assembly',
      startTime: '10:00',
      endTime: '10:15',
      dayOfWeek: 'Wednesday',
      duration: 15,
      color: '#8B5CF6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-28',
      title: 'Break',
      description: 'Morning break',
      startTime: '10:20',
      endTime: '10:35',
      dayOfWeek: 'Wednesday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-29',
      title: 'Maths Cont',
      description: 'Maths continuation',
      startTime: '10:35',
      endTime: '10:50',
      dayOfWeek: 'Wednesday',
      duration: 15,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-30',
      title: 'English Experience Day',
      description: 'English experience and activities',
      startTime: '11:00',
      endTime: '12:00',
      dayOfWeek: 'Wednesday',
      duration: 60,
      color: '#10B981',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-31',
      title: 'Lunch',
      description: 'Lunch break',
      startTime: '12:00',
      endTime: '13:00',
      dayOfWeek: 'Wednesday',
      duration: 60,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-32',
      title: 'Handwriting',
      description: 'Handwriting practice',
      startTime: '13:00',
      endTime: '13:15',
      dayOfWeek: 'Wednesday',
      duration: 15,
      color: '#6B7280',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-33',
      title: 'Maths Meeting',
      description: 'Maths meeting',
      startTime: '13:15',
      endTime: '13:20',
      dayOfWeek: 'Wednesday',
      duration: 5,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-34',
      title: 'Art',
      description: 'Drawing with detail – small objects',
      startTime: '13:20',
      endTime: '14:20',
      dayOfWeek: 'Wednesday',
      duration: 60,
      color: '#EC4899',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-35',
      title: 'RE',
      description: 'To know what a Mezuzah reminds Jewish people about.',
      startTime: '14:15',
      endTime: '15:00',
      dayOfWeek: 'Wednesday',
      duration: 45,
      color: '#A855F7',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-36',
      title: 'Storytime',
      description: 'Story time',
      startTime: '15:00',
      endTime: '15:15',
      dayOfWeek: 'Wednesday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // Thursday
    {
      id: 'block-37',
      title: 'Registration and Early Morning work',
      description: 'Daily registration and morning activities',
      startTime: '08:35',
      endTime: '08:50',
      dayOfWeek: 'Thursday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-38',
      title: 'RWI',
      description: 'Read Write Inc phonics',
      startTime: '09:00',
      endTime: '09:30',
      dayOfWeek: 'Thursday',
      duration: 30,
      color: '#3B82F6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-39',
      title: 'PE',
      description: 'Physical Education',
      startTime: '09:30',
      endTime: '10:00',
      dayOfWeek: 'Thursday',
      duration: 30,
      color: '#F97316',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-40',
      title: 'Singing Assembly',
      description: 'Singing assembly',
      startTime: '10:00',
      endTime: '10:15',
      dayOfWeek: 'Thursday',
      duration: 15,
      color: '#8B5CF6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-41',
      title: 'Break',
      description: 'Morning break',
      startTime: '10:20',
      endTime: '10:35',
      dayOfWeek: 'Thursday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-42',
      title: 'PE',
      description: 'Physical Education (continued)',
      startTime: '11:00',
      endTime: '12:00',
      dayOfWeek: 'Thursday',
      duration: 60,
      color: '#F97316',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-43',
      title: 'Lunch',
      description: 'Lunch break',
      startTime: '12:00',
      endTime: '13:00',
      dayOfWeek: 'Thursday',
      duration: 60,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-44',
      title: 'Handwriting',
      description: 'Handwriting practice',
      startTime: '13:00',
      endTime: '13:15',
      dayOfWeek: 'Thursday',
      duration: 15,
      color: '#6B7280',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-45',
      title: 'Maths Meeting',
      description: 'Maths meeting',
      startTime: '13:15',
      endTime: '13:50',
      dayOfWeek: 'Thursday',
      duration: 35,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-46',
      title: 'English',
      description: 'Sentence Stack 6',
      startTime: '13:50',
      endTime: '14:20',
      dayOfWeek: 'Thursday',
      duration: 30,
      color: '#10B981',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-47',
      title: 'Maths',
      description: 'Arithmetic Test',
      startTime: '14:20',
      endTime: '15:00',
      dayOfWeek: 'Thursday',
      duration: 40,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-48',
      title: 'Storytime',
      description: 'Story time',
      startTime: '15:00',
      endTime: '15:15',
      dayOfWeek: 'Thursday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },

    // Friday
    {
      id: 'block-49',
      title: 'Registration and Early Morning work',
      description: 'Daily registration and morning activities',
      startTime: '08:35',
      endTime: '08:50',
      dayOfWeek: 'Friday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-50',
      title: 'Celebration Assembly',
      description: 'Celebration assembly',
      startTime: '09:00',
      endTime: '09:30',
      dayOfWeek: 'Friday',
      duration: 30,
      color: '#8B5CF6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-51',
      title: 'RWI',
      description: 'Read Write Inc phonics',
      startTime: '09:30',
      endTime: '10:00',
      dayOfWeek: 'Friday',
      duration: 30,
      color: '#3B82F6',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-52',
      title: 'Break',
      description: 'Morning break',
      startTime: '10:20',
      endTime: '10:35',
      dayOfWeek: 'Friday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-53',
      title: 'English',
      description: 'Sentence Stacking 7',
      startTime: '10:35',
      endTime: '11:40',
      dayOfWeek: 'Friday',
      duration: 65,
      color: '#10B981',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-54',
      title: 'Maths',
      description: 'Test Revision',
      startTime: '11:40',
      endTime: '12:00',
      dayOfWeek: 'Friday',
      duration: 20,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-55',
      title: 'Lunch',
      description: 'Lunch break',
      startTime: '12:00',
      endTime: '13:00',
      dayOfWeek: 'Friday',
      duration: 60,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-56',
      title: 'Handwriting',
      description: 'Handwriting practice',
      startTime: '13:00',
      endTime: '13:15',
      dayOfWeek: 'Friday',
      duration: 15,
      color: '#6B7280',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-57',
      title: 'Maths',
      description: 'Test Revision',
      startTime: '13:15',
      endTime: '13:45',
      dayOfWeek: 'Friday',
      duration: 30,
      color: '#F59E0B',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-58',
      title: 'Catch Up Slot',
      description: 'Catch up time',
      startTime: '13:45',
      endTime: '14:35',
      dayOfWeek: 'Friday',
      duration: 50,
      color: '#6B7280',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-59',
      title: 'Whole Class Comprehension + TTRS',
      description: 'Times Tables Rock Stars',
      startTime: '14:15',
      endTime: '15:00',
      dayOfWeek: 'Friday',
      duration: 45,
      color: '#EC4899',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    },
    {
      id: 'block-60',
      title: 'Storytime',
      description: 'Story time',
      startTime: '15:00',
      endTime: '15:15',
      dayOfWeek: 'Friday',
      duration: 15,
      color: '#9CA3AF',
      timetableId: 'sample-1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    }
  ]
}
