[build]
  command = "./netlify-build.sh"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Clear Prisma cache before build
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable caching for Prisma-related files
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
